// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api-reference/authentication.mdx": () => import("../content/docs/api-reference/authentication.mdx?collection=docs"), "api-reference/flags.mdx": () => import("../content/docs/api-reference/flags.mdx?collection=docs"), "api-reference/sdk-endpoint.mdx": () => import("../content/docs/api-reference/sdk-endpoint.mdx?collection=docs"), "api-reference/webhooks.mdx": () => import("../content/docs/api-reference/webhooks.mdx?collection=docs"), "concepts/audit-history.mdx": () => import("../content/docs/concepts/audit-history.mdx?collection=docs"), "concepts/environments.mdx": () => import("../content/docs/concepts/environments.mdx?collection=docs"), "concepts/flags.mdx": () => import("../content/docs/concepts/flags.mdx?collection=docs"), "concepts/organizations-projects.mdx": () => import("../content/docs/concepts/organizations-projects.mdx?collection=docs"), "concepts/rollout.mdx": () => import("../content/docs/concepts/rollout.mdx?collection=docs"), "concepts/schedule-auto-rollout.mdx": () => import("../content/docs/concepts/schedule-auto-rollout.mdx?collection=docs"), "concepts/sse-realtime.mdx": () => import("../content/docs/concepts/sse-realtime.mdx?collection=docs"), "concepts/webhooks.mdx": () => import("../content/docs/concepts/webhooks.mdx?collection=docs"), "getting-started/create-first-flag.mdx": () => import("../content/docs/getting-started/create-first-flag.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "guides/ab-testing-with-rollout.mdx": () => import("../content/docs/guides/ab-testing-with-rollout.mdx?collection=docs"), "guides/canary-deploys.mdx": () => import("../content/docs/guides/canary-deploys.mdx?collection=docs"), "guides/migrate-from-env-vars.mdx": () => import("../content/docs/guides/migrate-from-env-vars.mdx?collection=docs"), "sdk/javascript/evaluate-flags.mdx": () => import("../content/docs/sdk/javascript/evaluate-flags.mdx?collection=docs"), "sdk/javascript/index.mdx": () => import("../content/docs/sdk/javascript/index.mdx?collection=docs"), "sdk/javascript/initialization.mdx": () => import("../content/docs/sdk/javascript/initialization.mdx?collection=docs"), "sdk/javascript/realtime-sse.mdx": () => import("../content/docs/sdk/javascript/realtime-sse.mdx?collection=docs"), "sdk/javascript/typescript-types.mdx": () => import("../content/docs/sdk/javascript/typescript-types.mdx?collection=docs"), }),
};
export default browserCollections;